
# ??tomcat???
server:
  error:
    path: "/error"

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
      enabled: true
      file-size-threshold: 1KB

  application:
    name: "prospect"

  profiles:
    active: @spring.profiles.active@

eureka:
  instance:
    appname: "PROSPECT"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 2000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

        spring:
          jackson:
            serialization:
              write-dates-as-timestamps: false
