
spring:

  datasource:
#    url: jdbc:mysql://192.168.1.10/c3_management
#    username: Editions
#    password: C3editions@_21
    url: jdbc:mysql://localhost/c3_management
    username: root
    password:
  mvc:
    format:
      date: "yyyy-MM-dd"
      date-time: "MM/dd/yyyy HH:mm:ss"


files.uploads: "C:/Users/User"

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8990/eureka"
